[project]
name = "parsing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.3.1",
    "ipykernel>=6.29.5",
    "pandas>=2.3.0",
    "pip>=25.1.1",
    "polars>=1.31.0",
    "pyarrow>=20.0.0",
]
